/**
 * ADDON REGISTRY EXAMPLE
 * ======================
 * This shows how the combiner skill internally maps add-on content.
 * You do NOT need to edit this — it is auto-generated by the skill.
 * Provided here as a reference for understanding the merge process.
 */

const ADDON_MAP = {

  // ── Example Add-on 1: Tree Cutter ─────────────────────────────
  treecutter: {
    namespace: "treecutter",
    bp_uuid: "a1b2c3d4-...",
    rp_uuid: "e5f6a7b8-...",
    min_engine: [1, 21, 0],
    script_api_version: "1.14.0",

    tools: {
      tree_cutter: ["treecutter:lumber_axe", "treecutter:mega_axe"],
      axe: [],
    },
    logs: ["treecutter:spirit_log", "treecutter:ash_log"],
    leaves: ["treecutter:spirit_leaves", "treecutter:ash_leaves"],
    saplings: ["treecutter:spirit_sapling"],
    misc_items: ["treecutter:spirit_sap"],

    loot_tables: [
      { path: "loot_tables/treecutter/forester_chest.json", context: "forest" },
      { path: "loot_tables/treecutter/hollow_tree_chest.json", context: "forest" },
    ],
    features: [],
    biomes: [],
    dimensions: [],
    mobs: [
      { id: "treecutter:wood_sprite", family_tags: ["passive"], loot_table: "loot_tables/treecutter/wood_sprite.json" }
    ],
  },

  // ── Example Add-on 2: Custom Metals ───────────────────────────
  custommetal: {
    namespace: "custommetal",
    bp_uuid: "c3d4e5f6-...",
    rp_uuid: "a7b8c9d0-...",
    min_engine: [1, 21, 0],
    script_api_version: "1.14.0",

    tools: {
      pickaxe: ["custommetal:stellite_pickaxe"],
      axe: ["custommetal:stellite_axe"],   // iron+ axe → also fells trees
    },
    ores: {
      stone:     ["custommetal:stellite_ore"],
      deepslate: ["custommetal:deepslate_stellite_ore"],
    },
    ingots:   ["custommetal:stellite_ingot"],
    nuggets:  ["custommetal:stellite_nugget"],
    raw_ores: ["custommetal:raw_stellite"],

    features: [
      { id: "custommetal:stellite_ore_feature", fill_block: "custommetal:stellite_ore",
        y_min: -64, y_max: 16, count: 8, dimension: "minecraft:overworld" },
      { id: "custommetal:deepslate_stellite_feature", fill_block: "custommetal:deepslate_stellite_ore",
        y_min: -64, y_max: -16, count: 5, dimension: "minecraft:overworld" },
    ],
    loot_tables: [
      { path: "loot_tables/custommetal/mine_chest.json", context: "mine" },
    ],
    biomes: [],
    dimensions: [],
    mobs: [],
  },

  // ── Example Add-on 3: Custom Farming ──────────────────────────
  customfarm: {
    namespace: "customfarm",
    bp_uuid: "b2c3d4e5-...",
    rp_uuid: "f6a7b8c9-...",
    min_engine: [1, 21, 0],

    tools: { hoe: ["customfarm:golden_hoe"] },
    crops:  ["customfarm:starwheat_crop"],
    foods:  ["customfarm:starwheat_bread", "customfarm:starwheat"],
    seeds:  ["customfarm:starwheat_seeds"],

    loot_tables: [
      { path: "loot_tables/customfarm/harvest_chest.json", context: "village" },
    ],
    mobs: [
      { id: "customfarm:friendly_golem", family_tags: ["passive","friendly"], loot_table: null }
    ],
    features: [],
    biomes: [],
    dimensions: [],
  },
};

/**
 * COMPAT CROSS-LINK RESULTS (auto-generated by skill after merge)
 *
 * Tree cutting:
 *   treecutter:lumber_axe + treecutter:mega_axe + custommetal:stellite_axe
 *   → all fell: treecutter:spirit_log, treecutter:ash_log + all vanilla logs
 *
 * Loot injection:
 *   custommetal:stellite_ingot (w:10), custommetal:raw_stellite (w:12)
 *   → injected into: treecutter:forester_chest, treecutter:hollow_tree_chest
 *
 *   treecutter:spirit_sap (w:6)
 *   → injected into: custommetal:mine_chest
 *
 *   customfarm:starwheat_bread (w:10), customfarm:starwheat_seeds (w:20)
 *   → injected into: treecutter:hollow_tree_chest, treecutter:forester_chest
 *
 * Cross-smelting:
 *   custommetal:raw_stellite → custommetal:stellite_ingot
 *   tags: ["furnace", "blast_furnace"]   ← expanded to all smelter tags found
 *
 * Mob harmony:
 *   customfarm:friendly_golem → protected from custommetal/treecutter hostile mobs
 *   treecutter:wood_sprite    → protected from custommetal/customfarm hostile mobs
 *
 * Wandering trader trades added:
 *   custommetal:stellite_ingot  for 5 emeralds
 *   customfarm:starwheat_bread  for 3 emeralds
 *   treecutter:spirit_sap       for 2 emeralds
 *
 * Ore Y-bands assigned (overworld):
 *   custommetal:stellite_ore          → y [-64,  -16]  (band 48)
 *   custommetal:deepslate_stellite_ore → y [-64,  -32]  (band 32)
 */

